### ISSUE TITLE
1.17 Snapshot

### ISSUE THREAD

**Issue by LifeLegend101** [19MisterX98/SeedcrackerX#12]
When I try to use this on 1.17, the game keeps to crash, is it possible for you to update it to the snapshots?

**Comment by 19MisterX98** [comment]
The rendering system of minecraft got updated and I dont know how to make the mod work with that. I can probably figure it out when litematica or some other mod updates so I can see how they did it. Wearblackallday or neil may update thier external dungeon crackers faster though since fixing them would be a five minute job.

**Comment by 19MisterX98** [comment]
https://github.com/WearBlackAllDay/SeedCandy
https://www.reddit.com/r/MinecraftAtHome/comments/j941w5
